module.exports = {
    Help: require('../helpCommands/A_Help'),
    Admin: require('../helpCommands/admin'),
    Misc: require('../helpCommands/misc'),
    Music: require('../helpCommands/music'),
    Kill: require('./kill'),
    CreateTicket: require('../ticketSystem/CreateTicket'),
    DeleteTicket: require('../ticketSystem/DeleteTicket'),
    Support: require('../support'),
    BugReport: require('../bugReport'),
    Update: require('../update'),
    He: require('../pronouns/he'),
    She: require('../pronouns/she'),
    They: require('../pronouns/they'), 
    Ban: require('../modCommands/ban'),
    Kick: require('../modCommands/kick'), 
    Play: require('../musicCommands/play'),
}